# Generated by Django 5.1 on 2024-08-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='artist',
            new_name='albom',
        ),
    ]
