# Generated by Django 5.1 on 2024-08-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_artist_songs_albom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='albom',
            new_name='artist',
        ),
    ]
