# Generated by Django 5.1 on 2024-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_albom_songs_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
