# Generated by Django 5.1 on 2024-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_songs_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albom',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.URLField(),
        ),
    ]
