# Generated by Django 5.1 on 2024-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_albom_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(),
        ),
    ]
