# Generated by Django 5.1 on 2024-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
