# Generated by Django 5.1 on 2024-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_songs_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='listen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='listen_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
