# Generated by Django 5.1 on 2024-08-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_albom_listen_count_artist_listen_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albom',
            old_name='listen_count',
            new_name='listen',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='listen_count',
            new_name='listen',
        ),
    ]
