# Generated by Django 5.1 on 2024-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_listen_count_albom_listen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=5),
        ),
    ]
