# Generated by Django 5.1 on 2024-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_songs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=5),
        ),
    ]
