# Generated by Django 5.1 on 2024-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_artist_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='albom',
            index=models.Index(fields=['id'], name='api_albom_id_d4fe9d_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['id'], name='api_artist_id_0571d6_idx'),
        ),
        migrations.AddIndex(
            model_name='songs',
            index=models.Index(fields=['id'], name='api_songs_id_318d14_idx'),
        ),
    ]
